### ISSUE TITLE
New version of HPO

### ISSUE THREAD

**Issue by Mellandd** [Centogene/pyhpo#10]
Hello,

last month HPO released an update. I tried to use the new version with this library but it seems that it cannot parse the ontology.

I tried to update the files with

```
from pyhpo.update_data import download_data
download_data()
```

and I also created a directory with the new files manually downloaded, but in both cases I get an error:

```
Traceback (most recent call last):
  File "*/pruebahpo.py", line 2, in <module>
    _ = Ontology()
  File "*/lib/python3.10/site-packages/pyhpo/ontology.py", line 51, in __call__
    self._load_from_obo_file(data_folder)
  File "*/lib/python3.10/site-packages/pyhpo/ontology.py", line 380, in _load_from_obo_file
    for term in terms_from_file(data_folder):
  File "*/lib/python3.10/site-packages/pyhpo/parser/obo.py", line 121, in terms_from_file
    yield parse_obo_section(term_section)
  File "*/lib/python3.10/site-packages/pyhpo/parser/obo.py", line 137, in parse_obo_section
    key, value = line.split(':', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

This error appears when I try to do:

```
from pyhpo import Ontology
_ = Ontology()

term = Ontology.get_hpo_object('Scoliosis')
print(term)
```

It would be a pity that this library could not be used with the new versions of HPO. It could also be that I did something wrong, but this exact script worked with the previous version of the ontology.

Thank you for your help.

**Comment by Mellandd** [comment]
Thank you very much!

I knew it had to be some change they made to the ontology. Luckily it was nothing too serious.
