### ISSUE TITLE
After install problem

### ISSUE THREAD

**Issue by EnricX** [Centogene/pyhpo#14]
Dear all.
I've just installed the package (via 'pip installl pyhpo', also tried 'pip install pyhpo[all]') on two different platforms: Linux Mint, Python 3.8, Spyder IDE and independently on a W11, Python 3.11.4 , IDLE environment.
On both devices I get this error when trying to use the library (Ontology, HPOSet...)

*************
 Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from pyhpo import Ontology
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyhpo\__init__.py", line 5, in <module>
    from pyhpo.term import HPOTerm
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyhpo\term.py", line 9, in <module>
    from pyhpo.similarity import SimScore
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyhpo\similarity\__init__.py", line 1, in <module>
    from pyhpo.similarity.base import SimScore
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyhpo\similarity\base.py", line 8, in <module>
    class _Similarity(BaseModel):
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_model_construction.py", line 95, in __new__
    private_attributes = inspect_namespace(
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_model_construction.py", line 328, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `kind = 'omim'`. All model fields require a type annotation; if `kind` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.0.1/u/model-field-missing-annotation
************

Thanks!

**Comment by anergictcell** [comment]
Hey @EnricX,

thanks for pointing out the issue. It is related to a newer `Pydantic` version, which is currently incompatible with PyHPO. I will try to create a fix in the coming days.
In the meantime, you can manually fix this by installing an older version of Pydantic first:
```bash
pip install pydantic==1.10.11
pip install pyhpo
```

**Comment by anergictcell** [comment]
I was able to fix it to use Pydantic 2.0 and created a new release. You should be able to install it normally now

**Comment by EnricX** [comment]
Hi, I've tried it and works like a charm with the new version. Thanks a lot!!
